### ISSUE TITLE
GCC Explorer DOS

### ISSUE THREAD

**Issue by mattgodbolt** [mattgodbolt/gcc-explorer#93]
GCC Explorer went down, and this is what was last in the logs:

```
Jan 13 11:18:47 ip-172-30-2-150 gcc:  /gcc-explorer/lib/compile.js:144 
Jan 13 11:18:47 ip-172-30-2-150 gcc:  RangeError: Invalid string length 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at Socket.emit (events.js:169:7) 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at readableAddChunk (_stream_readable.js:146:16) 
Jan 13 11:18:47 ip-172-30-2-150 gcc:          stderr += data; 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at Socket.<anonymous> (/gcc-explorer/lib/compile.js:144:19) 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at Socket.Readable.push (_stream_readable.js:110:10) 
Jan 13 11:18:47 ip-172-30-2-150 gcc:                    ^ 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at emitOne (events.js:77:13) 
Jan 13 11:18:47 ip-172-30-2-150 gcc:      at Pipe.onread (net.js:523:20) 
```

**Comment by mattgodbolt** [comment]
The following example will blow GCC explorer up:

```cpp
int main()
{
    return;
    #include __FILE__
    #include __FILE__
}
```
